[tox]
labels = 
    format = format-{md, py}
    lint = format-{md, py}, lint
    build = clean, _build

[testenv]
deps = 
    pytest
    coverage
commands =
    coverage run pytest -rs {posargs}
    coverage report --fail-under 100 --include tests/*

[testenv:format-py]
skip_install = true
deps = 
    ruff
commands = 
    ruff check --select I --fix {posargs:.}
    ruff format {posargs:.}

[testenv:format-md]
skip_install = true
deps = 
    mdformat
commands = 
    mdformat {posargs:.}

[testenv:lint]
skip_install = true
deps = 
    ruff
commands =
    ruff check --fix {posargs:.}

[testenv:clean]
skip_install = true
deps = pyclean
commands = pyclean {posargs:. --verbose}

[testenv:_build]
skip_install = true
deps = build
commands = python -m build -w
